// Package db is the Go SQLite data-access layer that replaces the Node
// app's lib/db.js, built on modernc.org/sqlite (pure Go, no CGo). Open
// brings a database at a given path (DefaultPath for the real
// /data/glp.db) to the current schema and runs the same additive
// migrations lib/db.js's getDb() runs on every start: InitSchema,
// FixSchema, MigrateMachineColumns, MigrateMachineTheme, EnsureInstallID.
// The legacy flat-JSON-to-SQLite migration (lib/db.js's migrate() against
// JSON_FILES) is deliberately NOT ported — every install this binary can
// run against is already on SQLite.
//
// database/sql normally pools connections, which would make SQLite pragmas
// (journal_mode, foreign_keys) apply inconsistently depending on which
// connection later runs a query; Open pins the returned *sql.DB to a single
// connection (SetMaxOpenConns(1)) to match better-sqlite3's single-connection
// semantics exactly, which costs nothing since SQLite is a single-writer
// database anyway.
//
// Schema fidelity against the Node original is enforced by
// db_schema_test.go, which compares this package's schema (column names,
// types, NOT NULL, defaults, primary-key position, and named indexes)
// against testdata/node_schema.json — a fixture generated by
// testdata/gen_node_schema.js, which drives lib/db.js's real
// initSchema()/migrateMachineColumns()/migrateMachineTheme()/
// ensureInstallId() against a live better-sqlite3 database rather than a
// hand-transcribed guess at the schema. Regenerate that fixture after any
// lib/db.js schema change.
package db
